### ISSUE TITLE
Lack pkl files for help!

### ISSUE THREAD

**Issue by Drjingluo** [mingruixia/MDD_ConnectomeGradient#3]
Dear Dr. Xia,
When we use the following code to get the "dataset.pkl" file from the neurosynth package:
"import neurosynth as ns
ns.dataset.download(path='.', unpack=True)"
The links if failed so we can't get "dataset.pkl" file for the subsequent  analysis, So if you could upload the  "dataset.pkl" file to the github. Thanks!
Dr. Jing Luo

**Comment by mingruixia** [comment]
Dear Dr. Luo,
Due to the large size of "dataset.pkl", it cannot be uploaded to the github. Plaese download it from the following link: 
https://pan.bnu.edu.cn/l/81XGhX
Mingrui
