### ISSUE TITLE
Undefined files

### ISSUE THREAD

**Issue by qian-999** [mingruixia/MDD_ConnectomeGradient#4]
Hi, professor xia

I'm sorry for bothering you.  When I conduct the analysis on step 0 GradientCalculation\surrogate_maps_g1_z_resampletrue.py, I don't know how to generate my coord_file (Line 4: coord_file = "voxel_coordinates.txt"). I also could not find the file of "FSaverage_inflated_32K.nv" in the last version of Brainnet-viewer (Line 471 of c_StatForGradient.m). Where can I find these .m and .nv files？Thank you for your help.

Best wishes to you.

**Comment by mingruixia** [comment]
Hi,
I have uploaded a script called "x_gen_voxelcoord.m" to the 0_GradientCalculation folder for generating the coordinate file. The "FSaverage_inflated_32K.nv" file can now be located in the "1_BetweenGroupStat" folder.
